imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
                    ini:
                        memory_limit: 512M
            tests:
                override:
                    -   command: "php -d memory_limit=512M -d xdebug.mode=coverage vendor/bin/phpunit --coverage-clover=docs/coverage.clover"
                        # - command: "composer phpunit"
                        # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                        coverage:
                            file: "docs/coverage.clover"
                            format: "php-clover"
    analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file    analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file"
