imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
            commands:
                - cd mvc/me/report && npm install
                - cd mvc/me/report && npm run build
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: "php -d memory_limit=2G -d XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=docs/coverage.clover"
            # -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
            # -   command: "echo 'Skipping PHPUnit for now'"
